[package]
name = "nextcore-apls"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []
vulkan = ["nextcore-gpu/vulkan"]

[dependencies]
nextcore-gpu = { git = "https://github.com/26x86/Nextcore-GPU.git", rev = "eaab9fcfded3a8ee298453397790f13edace5694" }
plist = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = { version = "2", default-features = false }

[dev-dependencies]

[[example]]
name = "sgpu_grant_vulkan"
required-features = ["vulkan"]
