[package]
name = "nextcore-apls"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
nextcore-gpu = { git = "https://github.com/26x86/Nextcore-GPU.git", tag = "26x86-Nextcore-GPU-v0.1.0" }
plist = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = { version = "2", default-features = false }

[dev-dependencies]
